name: Terraform

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    uses: sil-org/workflows/.github/workflows/terraform.yml@main
    with:
      terraform-version: '~> 1.0.0'
      test-dir: test

  tftest:
    name: 'Terraform Test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Install Terraform 1.7, which is the earliest that supports `terraform test`.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.7.5"

      - name: Test
        run: |
          terraform init
          terraform test -verbose
